spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    h2:
      console:
        enable: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
        show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

  application:
      name: "accounts"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    logs:
      application: ${spring.application.name}

    stream:
        bindings:
          sendCommunication-out-0:
            destination: send-communication
        kafka:
          binder:
            brokers:
              -localhost:9092

  profiles:
    active: "prod"
  graphql:
    graphql:
      enabled: true
server:
 port: 8081

eureka:
  instance:
   preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceURL:
      defaultZone: http://localhost:8070/eureka/
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000